apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80        #targetPort: 80 # nao precisa pois o port eh igual ao targetPort
      nodePort: 30000 #30000-32767
  selector:
    app: primeiro-pod