apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-noticias-deployment
spec:
  replicas: 1
  # info do pod
  template:
    metadata:
      name: db-noticias
      labels: 
        app: db-noticias
    spec:
      containers:
        - name: db-noticias-container
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-configmap
  selector:
    matchLabels:
    # deve ser igual ao labels contido em template (do pod)
      app: db-noticias