apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
spec:
  # info do pod
  template:
    metadata:
      name: portal-noticias
      labels: 
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
          livenessProbe:
            httpGet:
              path: /
              port: 80 # escopo do pod
            periodSeconds: 10
            failureThreshold: 3 # nr tentativas antes de reiniciar o container
            initialDelaySeconds: 20 # iniciar validacao apos inicio do container
          readinessProbe:
            httpGet:
              path: /
              port: 80 # escopo do pod
            periodSeconds: 10
            failureThreshold: 5 # nr tentativas antes de ignorar o readiness
            initialDelaySeconds: 3 # iniciar validacao apos inicio do container
          resources: # definindo recurso, que depois serah usado para config no Horizontal Pod Autoscaler
            requests:
              cpu: 10m

  replicas: 3
  selector:
    matchLabels:
    # deve ser igual ao labels contido em template (do pod)
      app: portal-noticias