apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sistema-noticias-statefulset
spec:
  replicas: 1
  template:
    # Definicoes do Pod
    metadata:
      labels:
        app: sistema-noticias
      name: sistema-noticias
    spec:
      containers:
        - name: sistema-noticias-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: sistema-configmap
          volumeMounts:
            - name: imagens
              mountPath: /var/www/html/uploads
            - name: sessao
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /
              port: 80 # escopo do pod
            periodSeconds: 10
            failureThreshold: 3 # nr tentativas antes de reiniciar o container
            initialDelaySeconds: 20 # iniciar validacao apos inicio do container
          readinessProbe:
            httpGet:
              path: /inserir_noticias.php
              port: 80 # escopo do pod
            periodSeconds: 10
            failureThreshold: 5 # nr tentativas antes de ignorar o readiness
            initialDelaySeconds: 3 # iniciar validacao apos inicio do container
      volumes:
        - name: imagens
          persistentVolumeClaim:
            claimName: imagens-pvc
        - name: sessao
          persistentVolumeClaim:
            claimName: sessao-pvc
  selector:
    matchLabels:
      app: sistema-noticias
  serviceName: svc-sistema-noticias