apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: NodePort  
  ports:
    - port: 80        #targetPort: 80 # nao precisa pois o port eh igual ao targetPort
      nodePort: 30001 #30000-32767
  selector:
    app: sistema-noticias